# Generated by Django 5.0.4 on 2024-04-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_transacao_options_alter_transacao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='unidades',
            field=models.IntegerField(default=0),
        ),
    ]
