# Generated by Django 5.0.3 on 2024-03-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nots',
            new_name='computador',
        ),
    ]
