# Generated by Django 5.0.3 on 2024-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_computador_data_entrada_alter_computador_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='computadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_entrada', models.DateField()),
                ('data_entrega', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='computador',
        ),
    ]
